### ISSUE TITLE
system/timers

### ISSUE THREAD

**Issue by eagle-provision** [define-private-public/stopwatch#1] opened 2016-12-22 20:01 UTC
Better use epochTime from the times module instead of system/timers, it seems to be more portable.

**Comment by define-private-public** [comment] 2016-12-23 19:32
I can see this being better than using `system/timers`, though I think it would go with changing everything that uses hard integers over to floats.  Do you think that's a good idea or not?

e.g. `msecs()` would return a float (in milliseconds) instead of an `int64`

**Comment by eagle-provision** [comment] 2016-12-24 02:36
`system/timers` miss-reports time for me both in Windows and in Wine. I initially decided to use it because it seemed more precise, but if `times` is precise enough for your use-case then it's probably worth the change.

**Comment by define-private-public** [comment] 2016-12-24 19:59
Okay, I'll make a fork of this using the epoch times, if you could do a comparison of one using epoch times and the other that would be good.

**Comment by define-private-public** [comment] 2016-12-24 20:35
Okay, there is a new branch called `epoch`.  Could you take `stopwatch.nim` and test it for me on windows and wine?  Make sure it's producing valid values.   First test it by running a side-by side comparison with the stopwatch from `master` and see if the values are correct.  Functions like `Stopwatch::lap()` now return the value in seconds instead of nanoseconds btw.  Also, all return types are now floats (no int64s), as it makes sense because of `epochTime()`'s return type.

**Comment by eagle-provision** [comment] 2016-12-24 22:59
This passes the tests. The only issue I was having is that in windows the precision is very low (the 1 second test reports 1.014s in windows, while in linux it reports roughly 1.0003s)

Reported the system/timers issue upstream. I would like to see what they tell us before replacing master with the epoch branch.

**Comment by define-private-public** [comment] 2016-12-25 02:47
Okay, thanks for testing.

I noticed when I ran the `epoch` version (on linux) that it was slightly less precise than the `system/timers` version, but it was well within margin.  I'll test this on OS X.

**Comment by define-private-public** [comment] 2016-12-25 03:28
The `epochTime()` seems to work on OS X.  In fact, it's even better than the original `system/timers` one.  Take a look:

![stopwatch-nim-os_x-comparison](https://cloud.githubusercontent.com/assets/4551425/21469606/64570acc-ca29-11e6-8eaa-e2ecff5ab339.png)

I was able to reproduce that error multiple times on OS X, whereas the `epochTime()` version did not have that issue.  (I'll go see if this is a problem on Linux too).  Can you see if you can get the error to happen on Windows & Wine please?  Just run the program a couple of times and see if there is a negative time result.

As for the precision of timing on OS X, both cases seem to be within 1-5 milliseconds.  Not bad for general purposes, but not highly precise either.

**Comment by define-private-public** [comment] 2016-12-25 03:32
Okay, I tried the `system/timers` version on Linux a few times.  No issues what so ever.

**Comment by eagle-provision** [comment] 2016-12-25 20:35
I was not using system/timers correctly, see https://github.com/nim-lang/Nim/issues/5146

**Comment by eagle-provision** [comment] 2016-12-25 21:17
For these two tests:
```
include "system/timers"
from os import sleep
for i in 0..<10:
  var t0 = getTicks()
  sleep(1000)
  var t1 = getTicks()
  echo float(t1 - t0) / 1_000_000_000
```
```
import times
from os import sleep
for i in 0..<10:
  var t0 = epochTime()
  sleep(1000)
  var t1 = epochTime()
  echo float(t1 - t0)
```
Haven't run into the negative time issue, and precision seems to be quite similar across linux/wine/windows. Wine's precision is lower and similar for both tests.

Could you run them in OS X to see if you notice a difference in precision and if you run into the negative time issue for system/timers?

**Comment by define-private-public** [comment] 2016-12-25 21:34
Sure, I'll do that later.

Should I then make a branch that doesn't use Nanos instead?

**Comment by eagle-provision** [comment] 2016-12-25 22:31
```
import times
from os import sleep
var acc = 0.0
for i in 0..<10000000:
  var t0 = epochTime()
  var t1 = epochTime()
  acc += t1 - t0
echo acc
```

```
include "system/timers"
from os import sleep
var acc = 0.0
for i in 0..<10000000:
  var t0 = getTicks()
  var t1 = getTicks()
  acc += (t1 - t0).float # edit: I tested with this version but it would be better to
                         # just accumulate nanos and convert to floats later.
echo acc / 1_000_000_000
```

For these I have run into a changing results and negative numbers in windows for the times test, whereas for the system/timers test I get similar non-negative results. So it's probably better to go for system/timers unless you run into negative results in OS X for this test (but I find that unlikely, as nim's GC relies on this)

**Comment by eagle-provision** [comment] 2016-12-25 23:01
So yes, Ticks instead of Nanos except for the accumulator.

**Comment by define-private-public** [comment] 2016-12-27 03:40
Alright, the output from the first blob of code (on OS X):

```
system/timers test:
1.002345398
1.002918669
1.005110985
1.00513397
1.003438279
1.005101516
1.002710685
1.005107712
1.003739181
1.001535732

times test:
1.005167961120605
1.003404855728149
1.005111932754517
1.005190849304199
1.005200862884521
1.003350973129272
1.005174160003662
1.005198001861572
1.00042200088501
1.005179166793823
```

And the second (I accumulated as `Nanos` and then converted to floats at the end):
```
epcohTime(): acc=0.6454029083251953
getTicks(): acc=0.34193186
```

I think maybe using `Nanos` is more efficient.  I'll get on that `Ticks` branch tomorrow.

**Comment by eagle-provision** [comment] 2016-12-27 16:24
But please do run the second test a few times to see if you get similar results every time. 

For example, running it 5 times in linux I get:
```
0.653878
0.654012
0.655459
0.654218
0.652757
```
(works perfectly)
and for epochTime in windows I get different results and even negative numbers (like 0.25, 0.31, -0.1, etc).

**Comment by define-private-public** [comment] 2016-12-28 01:23
Okay... running that second test again (multiple times) produced very similar results.  I also compiled it the first time with `debug` on.  These are the numbers I got when compiling with `release`:

```
epcohTime(): acc=0.58xxxxx
getTicks(): acc=0.22xxxxxx
```

**Comment by define-private-public** [comment] 2016-12-28 01:53
Alright, the `ticks` branch doesn't look good on OS X.  A lot of my runs of the `tester`  looked like this:

```
laps=@[]
total=0.0
laps=@[84]
total=1.005123862
1.00525865
total=1.00525865

total=1.506691877
0.501481709
0.501496583
total=1.506755233

7.4e-08
-4.189821841
-4.189744796
-4.189711353
total=-2.682949153
lapCount=2
lapCount=3
-4.189691916
-4.189686347
-4.084573181
total=-2.577817948

lapCount=3
L1=1.00525865
L2=0.501496583
all laps=@[501496583, -4084573181]
lapCount=2
----
lapCount=3
all laps(s)=@[1.00525865, 0.501496583, -4.084573181]

lapCount=0
total=0.012610972
total=2.7e-07
total(s)=0.253356915
total(m)=253
total(u)=253416
total(n)=253419663

bench(sleep(1000))=1.004859055
```

I don't think I'm using the API the wrong way.  If I am, then please tell me.  Right now, I'm thinking that maybe using `epochTime()` might be the safter bet as we don't get the negative time issues I've been seeing on OS X, despite it being slightly slower.

**Comment by eagle-provision** [comment] 2016-12-28 17:20
On the other hand, we get negative and inconsistent results with epochTime in windows .

[this](https://gist.github.com/rgv151/460fdc627cf0476ab1e1) test used to show the same negative number in OS X with my old stopwatch library. I ported it to the new stopwatch and added showing nsecs. Could you test it? I want to see if we see if nsecs tell us something about the problem.

Also, a minimalistic example (without using stopwatch) could come in handy in case we need to report it in the nim issue tracker. edit: done, see below.

```
import stopwatch

var c1, c2 = stopwatch()
for a in 1..10:
  bench(c1):
    for i in 0..1_000_000:
      var x = ""
      x = "Vietnam"
      x = ""
      x = "Cong Hoa Xa Hoi Chu Nghia VietNam"
  bench(c2):
    for i in 0..1_000_000:
      var x = newString(0)
      x = "Vietnam"
      x = newString(0)
      x = "Cong Hoa Xa Hoi Chu Nghia VietNam"

  echo "bench 1) secs: ", c1.secs, "\t\tbench 1) nsecs:", c1.nsecs
  echo "bench 2) secs: ", c2.secs, "\t\tbench 2) nsecs:", c1.nsecs
```

edit: This should, to the best of my knowledge, produce a negative result in OS X in at least some machines (better test with this one):

```
include "system/timers"

var c0, c1: Ticks

for a in 1..10:
  c0 = getTicks()
  for i in 0..1_000_000:
    var x = newString(0)
    x = "Vietnam"
    x = newString(0)
    x = "Cong Hoa Xa Hoi Chu Nghia VietNam"
  c1 = getTicks()

  echo "secs: ", float((c1 - c0).Nanos) / 1_000_000_000, "\t\t", "nsecs: ", (c1 - c0).Nanos
```

**Comment by eagle-provision** [comment] 2016-12-28 19:10
I strongly suspect of the [`-` proc](https://github.com/nim-lang/Nim/blob/devel/lib/system/timers.nim#L53) in system/timers.nim and the [numer, denom: int32](https://github.com/nim-lang/Nim/blob/devel/lib/system/timers.nim#L40) line (would try with int64).

**Comment by define-private-public** [comment] 2016-12-29 00:45
Yeah, I'm a little suspicious of that `-` proc when I was working on the `ticks` branch.

When using the `master` branch, the first test returns this:
```
bench 1) secs: -3.100705265		bench 1) nsecs:-3100705265
bench 2) secs: 1.239489151		bench 2) nsecs:-3100705265
bench 1) secs: 1.183014796		bench 1) nsecs:1183014796
bench 2) secs: 1.271733038		bench 2) nsecs:1183014796
bench 1) secs: -3.118866616		bench 1) nsecs:-3118866616
bench 2) secs: 1.243929538		bench 2) nsecs:-3118866616
bench 1) secs: 1.169243206		bench 1) nsecs:1169243206
bench 2) secs: -3.054938989		bench 2) nsecs:1169243206
bench 1) secs: 1.170836566		bench 1) nsecs:1170836566
bench 2) secs: 1.240379863		bench 2) nsecs:1170836566
bench 1) secs: 1.173894273		bench 1) nsecs:1173894273
bench 2) secs: -3.06035073		bench 2) nsecs:1173894273
bench 1) secs: 1.169726757		bench 1) nsecs:1169726757
bench 2) secs: 1.240456783		bench 2) nsecs:1169726757
bench 1) secs: 1.180532422		bench 1) nsecs:1180532422
bench 2) secs: -3.049529494		bench 2) nsecs:1180532422
bench 1) secs: 1.163955673		bench 1) nsecs:1163955673
bench 2) secs: 1.232715608		bench 2) nsecs:1163955673
bench 1) secs: -3.121181735		bench 1) nsecs:-3121181735
bench 2) secs: 1.236277877		bench 2) nsecs:-3121181735
```

As for that second test it didn't produce any negative results on my machine (a Mac Mini 2014).

**Comment by eagle-provision** [comment] 2016-12-29 02:38
[This](http://stackoverflow.com/questions/30199410/measure-elapsed-time-in-os-x/30203444#answer-30199775) stackoverflow answer says that the way system/timers is calculating Nanos can overflow (and -4.189821841 looks suspiciously similar to 2^32 = 4294967296)

So we can use times in OS X and system/timers for the rest, or report it/make a PR with the fix in nim's issue tracker.

**Comment by define-private-public** [comment] 2016-12-29 03:55
Ugh, having an OS X and a non-OS X codebase seems a little un-fun at the moment, but it might be the only thing we can do right now.

I'd say to report the overflow issue to the Nim people (it looks like something they would want to fix).  But for the time being we have a separate OS X code.

Also, what do you mean by using `times`?

**Comment by eagle-provision** [comment] 2016-12-29 05:04
`times` is the library gives you `epochTime`, I tend to refer to the libraries instead of the function.

The nim's GC doesn't use .Nanos, only getTicks, so this would not be high priority for them.

**Comment by define-private-public** [comment] 2016-12-29 07:45
Can you give me an example of the negative output on Windows/Wine coming from use of `epochTime()`.

**Comment by define-private-public** [comment] 2016-12-29 07:45
I'll make a `hybrid` branch that uses `getTicks()` on Linux & Windows,  `epochTime()` for OS X tomorrow.

**Comment by eagle-provision** [comment] 2016-12-29 15:26
```
import times
from os import sleep

var acc = 0.0

for i in 0..<10000000:
  var t0 = epochTime()
  var t1 = epochTime()
  acc += t1 - t0

echo acc
```
That's the test that showed a negative number and results that noticeably change in every run.

**Comment by eagle-provision** [comment] 2016-12-29 15:39
Ok, here's the output after about 25 runs:
```
0.2053232213947922
0.2868634938495234
0.2911319518461824
0.3012332766084001
0.1134112435393035
0.1547119343886152
0.1386491021839902
-0.06694710080046207
0.07292055629659444
0.04386777780018747
0.3495538961142302
0.4371763499220833
0.1511758855776861
```

**Comment by define-private-public** [comment] 2016-12-29 18:58
I still think that this issue with negative time should be reported to the nim developers.  It's a pretty bad bug.  Regardless if it comes from `epochTime()` or `getTicks()`.

**Comment by eagle-provision** [comment] 2016-12-29 19:23
Went on and reported the the `epochTime` issue. I don't feel like I should report the OS X one because I can't test it and I don't have a minimalistic example that only uses the `system/timers` library.

edit: here it is: https://github.com/nim-lang/Nim/issues/5165

**Comment by define-private-public** [comment] 2016-12-29 22:18
alright, the `hybrid` branch should be up.  for OS X, it provides an API that the 100% the same for the other two OSes.  

Please tell me if it works on Windows and then I'll merge the changes into `master`.  The only thing that is kind of sucky is the precision of it, but I'll leave a note in the README for users.

**Comment by eagle-provision** [comment] 2016-12-29 23:56
Tested in wine it didn't work (shows 0.01 seconds instead of 1 second for the 1 second test). Seems you are using the api incorrectly.

the object, at least for `system/timers`, should be like this:
```
type
  Stopwatch* = object
    running: bool
    startTicks: Ticks 
    laps: seq[Ticks]
    total: Nanos
```

**Comment by define-private-public** [comment] 2016-12-30 00:29
crap.  I'll get it fixed soon.

**Comment by define-private-public** [comment] 2016-12-30 00:39
Okay, that should have fixed it.  Try it again please.

**Comment by eagle-provision** [comment] 2016-12-30 00:50
I don't see any changes in the hybrid branch for some reason.

**Comment by eagle-provision** [comment] 2016-12-30 01:19
did you push?

**Comment by define-private-public** [comment] 2016-12-30 01:26
Did you clone from GitHub?  I put all pushes on the GitLab repo, and it syncs it once per hours.  I just did a force sync.  Try it now.

**Comment by eagle-provision** [comment] 2016-12-30 01:58
Seems to work well in windows. Precision looks low but I don't know what to blame (perhaps it's the sleep function)

```
laps=@[]
total=0.0
laps=@[0]
total=1.003450001
1.003598091
total=1.003598091

total=1.518080151
0.514800336
0.514859782
total=1.518457873

0.0
0.108585862
0.108750524
0.108794714
total=1.627287834
lapCount=2
lapCount=3
0.108939385
0.108973579
0.217853781
total=1.736311654

lapCount=3
L1=1.003598091
L2=0.514859782
all laps=@[514859782, 217853781]
lapCount=2
----
lapCount=3
all laps(s)=@[1.003598091, 0.514859782, 0.217853781]

lapCount=0
total=0.015054167
total=0.0
total(s)=0.264976702
total(m)=265
total(u)=265302
total(n)=265347322

bench(sleep(1000))=1.013729246
```

**Comment by define-private-public** [comment] 2016-12-30 02:23
i dunno, could also be if you compiled with debug instead of release.

Does it look good to merge `hybrid` into `master`?

**Comment by eagle-provision** [comment] 2016-12-30 02:54
I compiled with release.

>  Does it look good to merge hybrid into master?

Looks good to me.

**Comment by define-private-public** [comment] 2016-12-30 04:16
merged and pushed.  If you have any other ideas for increasing the precision, please tell.

I'll get started on that `turn lap off` thingy within a day or two.

**Closed as completed by define-private-public** 2016-12-30 04:16 UTC
